server:
  error:
    include-stacktrace: ALWAYS
  servlet:
    context-path: /
  port: 8001
  address: 0.0.0.0

spring:
  application:
    name: provider-hystrix
  mvc:
    throw-exception-if-no-handler-found: true

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/
  instance:
    instance-id: provider-hystrix-8001   #自定义服务名称信息,显示再eureka网页的status中
    prefer-ip-address: true     #访问路径可以显示IP地址

# http://1127.0.0.1:8001/actuator/info
info:
  app.name: provider-hystrix
  company.name: cloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$