server:
  error:
    include-stacktrace: ALWAYS
  servlet:
    context-path: /
  port: 9527
  address: 0.0.0.0

spring:
  application:
    name: gateway
  mvc:
    throw-exception-if-no-handler-found: true
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由功能，利用微服务名进行路由
          enabled: true
      routes:
        - id: provider8001-route
          # uri: http://localhost:8001
          # 动态路由
          uri: lb://provider-dept
          predicates:
            - Path=/dept/list
            - After=2021-01-31T18:47:58.954+08:00[Asia/Shanghai]

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/
  instance:
    instance-id: gateway-9527   #自定义服务名称信息,显示再eureka网页的status中
    prefer-ip-address: true     #访问路径可以显示IP地址

# http://1127.0.0.1:8001/actuator/info
info:
  app.name: provider-hystrix
  company.name: cloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$